// Compatibility endpoint for previously installed clients. New clients use /api/sync.
import {requireIdentity} from '@/lib/auth-server';
import {env} from 'cloudflare:workers';
import {z} from 'zod';
import {stateSchema,dateLocal} from '@/lib/time';
import {restoreState,diffState,type Snapshot} from '@/lib/sync-model';
import {getSupabaseState,mirrorForReminders,rpc} from '@/lib/supabase-state-server';
export async function GET(req:Request){try{const u=await requireIdentity(req);if(!u)return new Response(null,{status:401});const snapshot=await getSupabaseState(req,u.owner);await mirrorForReminders(u.owner,snapshot);const row=await env.DB!.prepare('SELECT version FROM time_accounts WHERE owner=?').bind(u.owner).first<{version:number}>();return Response.json({state:restoreState(snapshot.rows),version:row?.version??0},{headers:{'Cache-Control':'no-store'}});}catch{return Response.json({error:'Não foi possível carregar os registos. Tenta novamente.'},{status:503})}}
export async function PUT(req:Request){try{const u=await requireIdentity(req);if(!u)return new Response(null,{status:401});const body=z.object({state:stateSchema,version:z.number().int(),resetHistory:z.boolean().optional()}).parse(await req.json());const row=await env.DB!.prepare('SELECT version FROM time_accounts WHERE owner=?').bind(u.owner).first<{version:number}>();if(body.version!==(row?.version??0))return Response.json({error:'Os dados mudaram noutro dispositivo. Recarrega a página antes de guardar.'},{status:409});const before=await getSupabaseState(req,u.owner);const snapshot=await rpc(req,'zeitkonto_sync',{p_today:dateLocal(),p_changes:diffState(restoreState(before.rows),body.state,new Date().toISOString(),crypto.randomUUID())}) as Snapshot;await mirrorForReminders(u.owner,snapshot);const latest=await env.DB!.prepare('SELECT version FROM time_accounts WHERE owner=?').bind(u.owner).first<{version:number}>();return Response.json({state:restoreState(snapshot.rows),version:latest?.version??0});}catch{return Response.json({error:'Não foi possível guardar. Os campos foram mantidos.'},{status:400})}}
