import {test} from 'node:test';import assert from 'node:assert/strict';import {createRequire} from 'node:module';import {mkdtemp,rm} from 'node:fs/promises';import {tmpdir} from 'node:os';import {pathToFileURL} from 'node:url';
const require=createRequire(import.meta.url),{build}=createRequire(require.resolve('vite'))('esbuild'),dir=await mkdtemp(tmpdir()+'/zeit-sync-');const mods={};for(const name of ['sync-model','time']){await build({entryPoints:['lib/'+name+'.ts'],bundle:true,platform:'node',format:'esm',outfile:dir+'/'+name+'.mjs'});mods[name]=await import(pathToFileURL(dir+'/'+name+'.mjs'))}await rm(dir,{recursive:true});
const {diffState,restoreState}=mods['sync-model'],{empty,annualSummary}=mods.time;
const row={id:'a',date:'2026-12-24',kind:'holiday',holidayMode:'company_half',targetMinutes:480,includedPause:30,start:'',end:'',pause:0,delta:0,note:''};
test('offline roundtrip preserves all state, partial holidays and account settings',()=>{const s={...empty,records:[row],initial:12.5,holidayEntitlements:{2026:30},companyName:'Example',shifts:[{id:'shift1',date:'2026-12-23',name:'Night',start:'22:00',end:'06:00',targetMinutes:480}]};const changes=diffState(empty,s,'2026-09-13T10:00:00Z','op1');assert.deepEqual(restoreState(changes),s);assert.equal(annualSummary(restoreState(changes),2026,'2026-12-23').reserved,.5)});
test('retries are idempotent and unrelated concurrent changes survive',()=>{const a=diffState(empty,{...empty,records:[row]},'2026-09-13T10:00:00Z','a'),b=diffState(empty,{...empty,companyName:'Office'},'2026-09-13T10:01:00Z','b');const s=restoreState([...a,...a,...b]);assert.equal(s.records.length,1);assert.equal(s.companyName,'Office')});
test('newer edits win independently of arrival order, tombstones prevent resurrection',()=>{const a=diffState(empty,{...empty,records:[row]},'2026-09-13T10:00:00Z','a'),b=diffState({...empty,records:[row]},empty,'2026-09-13T10:01:00Z','b');assert.equal(restoreState([...b,...a]).records.length,0);const c={...a[0],value:{...row,note:'new'},updated_at:'2026-09-13T10:02:00Z',mutation_id:'c'};assert.equal(restoreState([c,...b,...a]).records[0].note,'new')});
test('work/vacation twin tombstone never hides the live row at the same timestamp',()=>{const a=diffState(empty,{...empty,records:[row]},'2026-09-13T10:00:00Z','a')[0],dead={...a,value:{},deleted_at:a.updated_at};assert.equal(restoreState([dead,a]).records.length,1);assert.equal(restoreState([a,dead]).records.length,1)});

test('timestamp ordering compares instants across ISO offsets',()=>{const a=diffState(empty,{...empty,companyName:'new'},'2026-09-13T10:00:00.100Z','a')[0];assert.equal(restoreState([a,{...a,value:'old',updated_at:'2026-09-13T10:00:00+00:00',mutation_id:'z'}]).companyName,'new')});
