import Link from 'next/link';
import {publisher} from '@/lib/publisher';
export const metadata={title:'Zeitkonto — Política de privacidade / Privacy policy'};
export default function PrivacyPage(){return <main className="auth-page"><article className="panel" style={{maxWidth:800,margin:'2rem auto',padding:24,lineHeight:1.7}}>
<h1>Zeitkonto — Política de privacidade</h1><p>Atualizada em 28 de setembro de 2026. Aplicável à aplicação Android e à versão web.</p>
<h2>Responsável e contacto</h2><p>A Zeitkonto é disponibilizada por {publisher.name} para registo pessoal do tempo. Para suporte, privacidade ou exercício de direitos: <a href={'mailto:'+publisher.email}>{publisher.email}</a>. Não envies palavras-passe, tokens, diagnósticos ou documentos médicos por email.</p>
<h2>Dados e finalidades</h2><p>Tratamos o email e identificador da conta para autenticação; nome e empresa, quando preenchidos; entradas, saídas, pausas, saldos, férias, ausências, notas e preferências para prestar o serviço e sincronizar os teus dispositivos. As credenciais são tratadas pelo serviço de autenticação Supabase. Não incluas informação de outras pessoas nas notas.</p>
<p>Os registos de doença são dados de saúde, mesmo sem diagnóstico. A criação ou alteração destes registos pede consentimento explícito. Não pedimos o diagnóstico nem o envio do atestado: apenas o tipo de ausência, datas e indicação de existência de atestado. Podes retirar o consentimento apagando os registos ou a conta, sem afetar o tratamento anterior à retirada.</p>
<h2>Localização, mapas e lembretes</h2><p>A deteção de chegada e saída é opcional. No Android utiliza a zona de trabalho configurada e a localização, incluindo em segundo plano quando autorizada. Não criamos um histórico contínuo dos teus percursos. A zona é protegida localmente pelo Android Keystore; os eventos confirmados tornam-se registos de trabalho que podem ser sincronizados. Podes desligar a deteção e retirar a permissão nas definições do telefone.</p>
<p>Ao abrir o mapa, os servidores de mosaicos OpenStreetMap recebem pedidos que revelam o endereço IP e a área visualizada. Ao pesquisar uma morada, a consulta é enviada ao serviço Photon da Komoot, que também recebe o IP. Estes serviços não são necessários para registar horas manualmente. A consulta de feriados ao Nager.Date passa pelo servidor e usa o país e ano selecionados.</p>
<p>Os lembretes usam as preferências de horário, idioma e fuso, bem como identificadores de entrega push quando ativados. O fornecedor de notificações do navegador/dispositivo participa na entrega. O sistema biométrico é o do Android: a app não recebe nem guarda impressões digitais.</p>
<h2>Estatísticas opcionais</h2><p>As estatísticas de utilização estão desativadas por defeito. Só após ativação em Definições recolhemos versão da app, plataforma, identificador lógico de dispositivo, último acesso e eventos das principais funcionalidades. Não incluímos horários individuais, notas ou conteúdo de ausências nos eventos. Podes desativar a recolha ou apagar as estatísticas anteriores nas definições. Não usamos estes dados para publicidade nem vendemos os teus dados.</p>
<h2>Fornecedores e armazenamento</h2><p>Usamos Supabase para autenticação e dados sincronizados; o projeto de base de dados está na região eu-central-1 (Alemanha). Cloudflare serve a aplicação e mantém uma cópia necessária aos lembretes em D1. A infraestrutura de entrega pode operar internacionalmente. O email de autenticação é entregue através do fornecedor configurado no Supabase. Os fornecedores de mapas e notificações recebem os dados necessários aos pedidos descritos acima. Consulta também as políticas de <a href="https://supabase.com/privacy">Supabase</a>, <a href="https://www.cloudflare.com/privacypolicy/">Cloudflare</a>, <a href="https://osmfoundation.org/wiki/Privacy_Policy">OpenStreetMap</a> e <a href="https://www.komoot.com/privacy">Komoot</a>.</p>
<p>O funcionamento offline guarda dados no dispositivo. A sessão e a cache web não devem ser consideradas um cofre com cifragem própria da app; protege o telefone com bloqueio de ecrã. A biometria restringe o acesso à interface e não substitui as proteções do sistema. As comunicações usam HTTPS. As políticas de acesso no servidor separam os dados por utilizador.</p>
<h2>Retenção e eliminação</h2><p>Conservamos os registos enquanto mantiveres a conta ou até os apagares. O histórico de alterações é limitado a 300 entradas; quando apagas um registo na app, o seu conteúdo é removido desse histórico, mantendo apenas a referência técnica da eliminação. Os eventos estatísticos têm retenção de 90 dias, sujeita à execução da manutenção; hashes de entregas de lembretes, sete dias.</p>
<p>A eliminação de conta remove os dados ativos associados no Supabase e a cópia auxiliar no fluxo da app. A manutenção reconcilia também contas removidas diretamente no serviço de autenticação. Uma marca técnica pseudonimizada impede a recriação por pedidos antigos durante 30 dias. Falhas temporárias dos fornecedores podem atrasar a reconciliação e a limpeza. Cópias de segurança e logs operacionais seguem os ciclos de retenção dos fornecedores e não são apagados instantaneamente com os dados ativos; contacta-nos para esclarecer os prazos aplicáveis ao teu pedido.</p>
<p>Dispositivos offline só recebem a eliminação quando voltam a comunicar. Termina sessão e limpa os dados locais em dispositivos antigos. Exportações PDF/CSV e ficheiros que partilhas ficam sob o teu controlo e não podem ser apagados remotamente pela Zeitkonto.</p>
<h2>Escolhas e direitos</h2><p>O tratamento necessário ao serviço permite executar o serviço solicitado; as estatísticas opcionais e os registos de doença dependem do teu consentimento. Usamos controlos técnicos de segurança para proteger contas e impedir abuso. Podes pedir acesso, correção, portabilidade, eliminação, limitação ou oposição, quando aplicável, e reclamar junto da autoridade de proteção de dados competente. O contacto acima recebe estes pedidos; poderemos pedir verificação proporcional da identidade, nunca a tua palavra-passe.</p>
<p>A eliminação está disponível na app e na página pública <Link href="/delete-account">Eliminar conta</Link>. Exige autenticação e confirmação para evitar pedidos de terceiros. Não existe compra ou pagamento real integrado nesta versão. Alterações relevantes a esta política serão comunicadas na app; quando necessário, será pedido novo consentimento.</p>
<p><Link href="/support">Suporte</Link> · <Link href="/">Voltar à Zeitkonto</Link></p>
</article></main>;}
