import {messages} from './i18n';
const rows:Record<string,[string,string,string]>={
 'Eliminar conta':['Konto löschen','Delete account','Hesabı sil'],
 'Não foi possível terminar sessão em segurança. Tenta novamente.':['Sichere Abmeldung fehlgeschlagen. Bitte erneut versuchen.','Could not sign out safely. Please retry.','Güvenli çıkış yapılamadı. Tekrar dene.'],
};
for(const [key,[de,en,tr]] of Object.entries(rows)){messages[key]={de,en,tr};}
export const accountTexts={
 pt:{title:'Eliminar conta Zeitkonto',detail:'Elimina permanentemente a conta, registos de trabalho, férias, doença, saldos, definições e analytics associados. A cópia dos lembretes e os registos locais ainda não sincronizados neste dispositivo serão apagados. Esta ação não pode ser desfeita.',password:'Palavra-passe',confirm:'Escreve DELETE para confirmar',button:'Eliminar definitivamente',busy:'A eliminar…',done:'Conta eliminada.',error:'Não foi possível concluir. Verifica a ligação e as credenciais e tenta novamente nesta página.',local:'A conta foi eliminada no servidor, mas a limpeza local não ficou completa. Limpa os dados da app nas definições Android e os dados do site.',retention:'Uma marca técnica sem email ou registos impede que pedidos antigos recriem a cópia auxiliar. Os backups seguem os prazos dos fornecedores. Nos restantes dispositivos, termina a sessão e limpa os dados da app ou do site.',back:'Voltar à app'},
 de:{title:'Zeitkonto-Konto löschen',detail:'Konto, Arbeitszeiten, Urlaub, Krankheit, Salden, Einstellungen und Nutzungsdaten werden dauerhaft gelöscht. Die Erinnerungskopie und nicht synchronisierte lokale Einträge auf diesem Gerät werden entfernt. Dies kann nicht rückgängig gemacht werden.',password:'Passwort',confirm:'Zur Bestätigung DELETE eingeben',button:'Endgültig löschen',busy:'Wird gelöscht…',done:'Konto gelöscht.',error:'Nicht abgeschlossen. Verbindung und Zugangsdaten prüfen und hier erneut versuchen.',local:'Das Serverkonto wurde gelöscht, lokale Daten konnten nicht vollständig entfernt werden. App-Daten in Android und Website-Daten löschen.',retention:'Eine technische Markierung ohne E-Mail oder Einträge verhindert das Wiederherstellen durch alte Anfragen. Backups folgen den Fristen der Anbieter. Auf anderen Geräten abmelden und App- oder Website-Daten löschen.',back:'Zur App'},
 en:{title:'Delete Zeitkonto account',detail:'Permanently deletes your account, work entries, leave, sickness, balances, settings and analytics. The reminder copy and unsynced local entries on this device are removed. This cannot be undone.',password:'Password',confirm:'Type DELETE to confirm',button:'Delete permanently',busy:'Deleting…',done:'Account deleted.',error:'Could not complete. Check your connection and credentials, then retry here.',local:'The server account was deleted, but local cleanup was incomplete. Clear Android app data and website data.',retention:'A technical marker without email or entries prevents old requests from recreating the auxiliary copy. Backups follow provider retention periods. On other devices, sign out and clear app or website data.',back:'Back to app'},
 tr:{title:'Zeitkonto hesabını sil',detail:'Hesabı, çalışma kayıtlarını, izinleri, hastalık kayıtlarını, bakiyeleri, ayarları ve kullanım verilerini kalıcı olarak siler. Hatırlatma kopyası ve bu cihazdaki eşitlenmemiş kayıtlar da silinir. Bu işlem geri alınamaz.',password:'Şifre',confirm:'Onaylamak için DELETE yaz',button:'Kalıcı olarak sil',busy:'Siliniyor…',done:'Hesap silindi.',error:'Tamamlanamadı. Bağlantıyı ve giriş bilgilerini kontrol edip tekrar dene.',local:'Sunucu hesabı silindi ancak yerel temizlik tamamlanamadı. Android uygulama verilerini ve site verilerini temizle.',retention:'E-posta veya kayıt içermeyen teknik bir işaret, eski isteklerin kopyayı yeniden oluşturmasını engeller. Yedekler sağlayıcının saklama süresine tabidir. Diğer cihazlarda oturumu kapatıp uygulama veya site verilerini temizle.',back:'Uygulamaya dön'}
};
