import {reconcileDeletedAccounts} from '@/lib/account-reconciliation-server';
import {accountBlocked} from '@/lib/account-deletion';
import {env} from 'cloudflare:workers';
import {stateSchema} from '@/lib/time';
import {wallTime} from '@/lib/push-schema';
import {reminderEvents} from '@/lib/shifts';
import {hashId,sendPush} from '@/lib/push-server';
import {translate} from '@/lib/i18n';
import '@/lib/shift-i18n';
export async function POST(req:Request){if(!env.REMINDER_CRON_TOKEN||req.headers.get('Authorization')!=='Bearer '+env.REMINDER_CRON_TOKEN)return new Response(null,{status:401});if(!env.DB)return new Response(null,{status:503});const db=env.DB,now=Date.now();let cursor='',sent=0,failed=0,accounts=0;
 try{await reconcileDeletedAccounts();while(true){const rows=await db.prepare("SELECT owner,payload FROM time_accounts WHERE owner>? AND json_array_length(json_extract(payload,'$.pushDevices'))>0 ORDER BY owner LIMIT 50").bind(cursor).all<{owner:string;payload:string}>();if(!rows.results.length)break;for(const row of rows.results){cursor=row.owner;accounts++;const parsed=stateSchema.safeParse(JSON.parse(row.payload));if(!parsed.success)continue;const data=parsed.data;for(const device of data.pushDevices){if(device.expirationTime&&device.expirationTime<now)continue;const endpointId=await hashId(device.endpoint);if(await db.prepare('SELECT id FROM push_deliveries WHERE id=?').bind('disabled:'+endpointId).first())continue;const wall=wallTime(now,device.timezone),activeDate=data.active?wallTime(data.active.start,device.timezone).date:null;for(const event of reminderEvents(data,wall.at,activeDate,120000)){const id=await hashId(row.owner+endpointId+event.key);const claim=await db.prepare('INSERT OR IGNORE INTO push_deliveries (id,created) VALUES (?,?) RETURNING id').bind(id,now).first();if(!claim)continue;try{if(await accountBlocked(db,row.owner))continue;const result=await sendPush(device,translate(device.lang,event.type==='entry'?'Está na hora de registar a entrada.':'Está na hora de registar a saída.'),'zeitkonto-'+event.key);if(result.status===404||result.status===410){await db.prepare('INSERT OR IGNORE INTO push_deliveries (id,created) VALUES (?,?)').bind('disabled:'+endpointId,now).run();}else if(!result.ok)throw Error('Push provider rejected request');else sent++;}catch{failed++;await db.prepare('DELETE FROM push_deliveries WHERE id=?').bind(id).run();}}}}if(rows.results.length<50)break;}
 await db.prepare('DELETE FROM push_deliveries WHERE created<?').bind(now-7*86400000).run();return Response.json({sent,failed,accounts},{headers:{'Cache-Control':'no-store'}});}catch{console.error('Reminder dispatch failed');return Response.json({sent,failed,error:'Dispatch unavailable'},{status:503})}}
