'use client';
import '@/lib/shift-i18n';
import '@/lib/improvements-i18n';
import {History,CalendarClock,CalendarDays,Wallet,Clock3,Home,Settings2,Palmtree,Coffee,HeartPulse,LogOut,X} from 'lucide-react';
import {Sidebar,SidebarHeader,SidebarContent,SidebarFooter,SidebarMenu,SidebarMenuItem,SidebarMenuButton,useSidebar} from '@/components/ui/sidebar';
import {translate,type Language} from '@/lib/i18n';
import type {LeaveKind} from '@/lib/time';
export function AppNavigation({lang,tab,onNavigate,onAdd,onSignOut,busy,email}:{lang:Language;tab:string;onNavigate:(tab:string)=>void;onAdd:(kind:LeaveKind)=>void;onSignOut:()=>Promise<void>;busy:boolean;email:string}){
 const {setOpenMobile}=useSidebar(),t=(s:string)=>translate(lang,s);
 const go=(action:()=>void)=>{setOpenMobile(false);action()};
 return <Sidebar className="zeit-sidebar"><SidebarHeader className="zeit-sidebar-header"><span className="brand"><span className="logo"><img src="/icons/icon-192.png?v=2" alt="" width={40} height={40} style={{borderRadius:10}}/></span>Zeitkonto</span><button type="button" className="mobile-menu-close" aria-label={t('Fechar menu')} onClick={()=>setOpenMobile(false)}><X size={22}/></button></SidebarHeader><SidebarContent><nav aria-label={t('Menu principal')}><SidebarMenu>{[{id:'today',label:'Página principal',Icon:Home},{id:'balances',label:'Férias e horas',Icon:Wallet},{id:'calendar',label:'Calendário',Icon:CalendarDays},{id:'shifts',label:'Lembretes',Icon:CalendarClock},{id:'history',label:'Resumo semanal',Icon:Clock3},{id:'changes',label:'Histórico de alterações',Icon:History},{id:'settings',label:'Definições',Icon:Settings2}].map(({id,label,Icon})=><SidebarMenuItem key={id}><SidebarMenuButton isActive={tab===id} aria-current={tab===id?'page':undefined} onClick={()=>go(()=>onNavigate(id))}><Icon/><span>{t(label)}</span></SidebarMenuButton></SidebarMenuItem>)}<li className="nav-group-label">{t('Marcar ausências')}</li>{[{kind:'holiday' as const,label:'Marcar férias',Icon:Palmtree},{kind:'rest' as const,label:'Usar horas acumuladas',Icon:Coffee},{kind:'sick_no_note' as const,label:'Registar doença',Icon:HeartPulse}].map(({kind,label,Icon})=><SidebarMenuItem key={kind}><SidebarMenuButton disabled={busy} onClick={()=>go(()=>onAdd(kind))}><Icon/><span>{t(label)}</span></SidebarMenuButton></SidebarMenuItem>)}</SidebarMenu></nav></SidebarContent><SidebarFooter className="zeit-sidebar-footer"><p>{email}</p><SidebarMenu><SidebarMenuItem><SidebarMenuButton disabled={busy} onClick={()=>go(()=>{void onSignOut()})}><LogOut/><span>{t('Terminar sessão')}</span></SidebarMenuButton></SidebarMenuItem></SidebarMenu></SidebarFooter></Sidebar>
}
