'use client';
import {HolidayDuration} from './holiday-duration';
import {displayDays} from '@/lib/holiday-label';
import {holidayTotal,holidayDuration,type Entry} from '@/lib/time';
import {useState} from 'react';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select';
import {Checkbox} from '@/components/ui/checkbox';
import {type State,type LeaveKind,isSick,balance,timeBalance,annualSummary} from '@/lib/time';
import {type Language,translate,formatMinutes,locales} from '@/lib/i18n';
import {dateRange,planLeave,germanRegions} from '@/lib/leave';
import {useHolidays} from '@/lib/use-holidays';
export function BulkLeave({data,lang,date,kind,onClose,save,busy}:{data:State;lang:Language;date:string;kind:LeaveKind;onClose:()=>void;save:(s:State)=>Promise<boolean|undefined>;busy:boolean}){
 const [holidayMode,setHolidayMode]=useState<'full'|'half'|'hours'|'company_half'>('full'),[holidayMinutes,setHolidayMinutes]=useState(Math.min(240,data.dailyMinutes));
 const t=(s:string,v:Record<string,string|number>={})=>translate(lang,s,v),[from,setFrom]=useState(date),[to,setTo]=useState(date),[type,setType]=useState(kind),[skipWeekend,setSkipWeekend]=useState(!isSick(kind)),[skipHoliday,setSkipHoliday]=useState(!isSick(kind)),[note,setNote]=useState(''),[error,setError]=useState('');
 let valid=true;try{dateRange(from,to)}catch{valid=false}const years=valid?Array.from(new Set([Number(from.slice(0,4)),Number(to.slice(0,4))])):[new Date().getFullYear()],h=useHolidays(data.country,years);
 const plan=valid?planLeave(from,to,data.records,h.rows,data.region,skipWeekend,skipHoliday):{dates:[],weekends:0,holidays:0,existing:0};
 const vacation=annualSummary(data,Number(from.slice(0,4))),clock=timeBalance(data);
 const debit=type==='rest'?Math.round(data.restCost*60)*plan.dates.length:0,remaining=balance(data)-debit,waiting=skipHoliday&&(h.loading||h.error),country=new Intl.DisplayNames([locales[lang]],{type:'region'}).of(data.country);
 const targets=plan.dates.map(date=>data.shifts.find(s=>s.date===date)?.targetMinutes??data.dailyMinutes),maxHoliday=Math.min(...targets,1440);
 const invalidHours=type==='holiday'&&holidayMode==='hours'&&(holidayMinutes<1||holidayMinutes>maxHoliday);
 const newRecords=plan.dates.map((date,i)=>({id:date,date,kind:type,targetMinutes:targets[i],includedPause:data.includedPause,start:'',end:'',pause:0,delta:type==='rest'?-Math.round(data.restCost*60):0,note,...(type==='holiday'?{holidayMode,holidayMinutes}:{} )} satisfies Entry));
 const holidayYears=[...new Set(plan.dates.map(d=>d.slice(0,4)))];
 async function submit(e:React.FormEvent){e.preventDefault();setError('');if(!valid||waiting||!plan.dates.length||invalidHours||type==='rest'&&remaining<0)return;const records=newRecords.map(r=>({...r,id:crypto.randomUUID()}));if(await save({...data,records:[...data.records,...records]}))onClose();else setError('Não foi possível guardar o período. Tenta novamente.');}

 return <Dialog open onOpenChange={o=>{if(!o&&!busy)onClose()}}><DialogContent className="entry-dialog"><DialogHeader><DialogTitle>{t('Marcar período')}</DialogTitle><DialogDescription>{t('Confirma o tipo de ausência e os dias antes de guardar.')}</DialogDescription></DialogHeader><form onSubmit={submit}>
 <label>{t('Tipo de registo')}<Select value={type} disabled={busy} onValueChange={v=>{setType(v as LeaveKind);setSkipWeekend(!isSick(v as LeaveKind));setSkipHoliday(!isSick(v as LeaveKind))}}><SelectTrigger className="select-input"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="holiday">{t('Férias')}</SelectItem><SelectItem value="rest">{t('Descanso com horas acumuladas')}</SelectItem><SelectItem value="sick_note">{t('Doença com atestado')}</SelectItem><SelectItem value="sick_no_note">{t('Doença sem atestado')}</SelectItem></SelectContent></Select></label>
 <div className="field-row"><label>{t('De')}<input type="date" min="2020-01-01" max="2035-12-31" required value={from} disabled={busy} onChange={e=>{setFrom(e.target.value);if(e.target.value>to)setTo(e.target.value)}}/></label><label>{t('Até')}<input type="date" min={from||'2020-01-01'} max="2035-12-31" required value={to} disabled={busy} onChange={e=>setTo(e.target.value)}/></label></div>
 {type==='holiday'&&<><HolidayDuration mode={holidayMode} minutes={holidayMinutes} lang={lang} max={maxHoliday} onChange={(mode,minutes)=>{setHolidayMode(mode);setHolidayMinutes(minutes)}}/><p className="muted">{t('A duração escolhida aplica-se a cada data selecionada. As horas são convertidas em dias pelas horas previstas de cada data.')}</p>{invalidHours&&<p className="error">{t('As horas de férias não podem ultrapassar as horas previstas do dia.')}</p>}</>}
 <label className="check-row"><Checkbox checked={skipWeekend} disabled={busy} onCheckedChange={v=>setSkipWeekend(v===true)}/>{t('Excluir sábados e domingos')}</label><label className="check-row"><Checkbox checked={skipHoliday} disabled={busy} onCheckedChange={v=>setSkipHoliday(v===true)}/>{t('Excluir feriados')}</label>
 <p className="muted">{country} · {data.region?(germanRegions[data.region]??data.region):t('Apenas feriados nacionais')}. {t('Altera o país e a região no calendário.')}</p>
 {!valid&&<p className="error">{t('Escolhe um período válido, até 366 dias.')}</p>}{h.loading&&<p role="status" className="muted">{t('A carregar feriados…')}</p>}{h.error&&<div className="error">{t('Não foi possível carregar os feriados.')} <button type="button" onClick={h.retry}>{t('Tentar novamente')}</button></div>}
 <div className="period-preview" aria-live="polite">{type==='rest'&&<p>{t("Saldo de horas atual")}: {formatMinutes(lang,clock.current)} · {t("Horas reservadas")}: {formatMinutes(lang,clock.reserved)} · {t("Horas livres para marcar")}: {formatMinutes(lang,clock.available)}</p>}{type==='holiday'&&<p>{t("Usadas até hoje")}: {displayDays(vacation.used,lang)} · {t("Marcadas para o futuro")}: {displayDays(vacation.reserved,lang)} · {t("Livres para marcar")}: {vacation.remaining===null?t("Por definir"):displayDays(vacation.remaining,lang)}</p>}{type==='holiday'&&holidayYears.map(year=>{const debit=holidayTotal(newRecords.filter(r=>r.date.startsWith(year))),before=annualSummary(data,Number(year)).remaining;return <p key={year}><b>{year} · {t('Desconto no saldo de férias')}: {displayDays(debit,lang)} {t('dias')}</b> · {formatMinutes(lang,newRecords.filter(r=>r.date.startsWith(year)).reduce((n,r)=>n+holidayDuration(r),0))}<br/>{t('Livres para marcar')}: {before===null?t('Por definir'):displayDays(before-debit,lang)}</p>})}<strong>{waiting?'…':plan.dates.length} {t('dias a marcar')}</strong><p>{t('Excluídos')}: {plan.weekends} {t('dias de fim de semana')} · {plan.holidays} {t('feriados')} · {plan.existing} {t('dias já registados')}</p>{type==='rest'?<><p>{t('Desconto')}: {formatMinutes(lang,debit)}</p><p>{t('Horas livres após marcação')}: <b>{formatMinutes(lang,remaining)}</b></p>{remaining<0&&<p className="negative">{t('Não tens horas suficientes para este período.')}</p>}</>:<p>{t(isSick(type)?'A doença não altera o saldo de horas nem desconta dias de férias.':'Este período de férias não altera o saldo de horas.')}</p>}{!waiting&&plan.dates.length>0&&<details><summary>{t('Ver dias incluídos')}</summary><div className="included-dates">{plan.dates.map(d=><span key={d}>{new Date(d+'T12:00:00').toLocaleDateString(locales[lang])}</span>)}</div></details>}</div>
 <p className="muted">{t(type==='rest'?'Os dias futuros reservam horas; o saldo atual só diminui na data marcada. Os registos existentes são mantidos.':'Os dias já registados são mantidos. Para alterar um dia existente, edita-o no calendário.')}</p><label>{t('Nota (opcional)')}<textarea maxLength={1000} value={note} disabled={busy} onChange={e=>setNote(e.target.value)}/></label>{error&&<p className="error" role="alert">{t(error)}</p>}<button className="primary wide" disabled={busy||!valid||waiting||invalidHours||!plan.dates.length||type==='rest'&&remaining<0}>{busy?t('A guardar…'):t('Guardar período')}</button></form></DialogContent></Dialog>
}
