'use client';
import {holidayLabel} from '@/lib/holiday-label';
import {useState} from 'react';
import {recordSchema,shiftSchema,type State} from '@/lib/time';
import {AlertDialog,AlertDialogContent,AlertDialogHeader,AlertDialogTitle,AlertDialogDescription,AlertDialogFooter,AlertDialogCancel,AlertDialogAction} from '@/components/ui/alert-dialog';
import {translate,locales,formatMinutes,type Language} from '@/lib/i18n';
import '@/lib/improvements-i18n';
export function ChangeHistory({data,lang,busy,save}:{data:State;lang:Language;busy:boolean;save:(s:State)=>Promise<boolean>}){const t=(s:string)=>translate(lang,s),[restore,setRestore]=useState<State['changes'][number]|null>(null),[error,setError]=useState('');
 const describe=(raw:string|null,kind:string)=>{if(!raw)return '—';try{const v=JSON.parse(raw);if(kind==='record'&&v.kind==='holiday')return `${v.date} · ${holidayLabel(recordSchema.parse(v),lang)}${v.note?' · '+v.note:''}`;return kind==='record'?`${t({work:'Turno de trabalho',holiday:'Férias',rest:'Descanso compensatório',sick_note:'Doença com atestado',sick_no_note:'Doença sem atestado'}[v.kind as string]||'Registo')} · ${v.date} · ${v.start||''} ${v.end||''} · ${v.pause} min · ${t('Horas previstas por dia')}: ${formatMinutes(lang,v.targetMinutes??480)} · ${formatMinutes(lang,v.delta)}${v.note?' · '+v.note:''}`:kind==='shift'?`${v.name} · ${v.date} · ${v.start}–${v.end} · ${formatMinutes(lang,v.targetMinutes??480)}`:kind==='active'?(v.pauseStart?t('Em pausa'):t('A trabalhar')):`${t('Horas previstas por dia')}: ${formatMinutes(lang,v.dailyMinutes??480)} · ${t('Saldo inicial')}: ${formatMinutes(lang,v.initial*60)} · ${t('Nome da empresa')}: ${v.companyName}`;}catch{return '—'}};
 async function recover(){if(!restore?.before)return;setError('');try{if(restore.kind==='record'){const old=recordSchema.parse(JSON.parse(restore.before));if(data.records.some(r=>r.date===old.date&&r.id!==old.id))throw Error('Já existe um registo nesta data.');if(await save({...data,records:[...data.records.filter(r=>r.id!==old.id),old]}))setRestore(null);}else if(restore.kind==='shift'){const old=shiftSchema.parse(JSON.parse(restore.before));if(data.shifts.some(s=>s.date===old.date&&s.id!==old.id))throw Error('Já existe um turno numa das datas. Nenhum turno foi alterado.');if(await save({...data,shifts:[...data.shifts.filter(s=>s.id!==old.id),old]}))setRestore(null);}}catch(e){setError((e as Error).message)}}
 return <section className="panel"><h2>{t('Histórico de alterações')}</h2><p className="muted">{t('Últimas 300 alterações, registadas a partir desta atualização. Repor a app a zero também apaga este histórico.')}</p>{!data.changes.length?<p className="empty">{t('Ainda não há alterações registadas.')}</p>:data.changes.map(c=><article className="record" key={c.id}><div className="record-info"><b>{t(c.kind==='record'?'Registo':c.kind==='shift'?'Turno planeado':c.kind==='active'?'Turno em curso':'Definições')} · {t(c.action==='add'?'Criado':c.action==='delete'?'Apagado':'Alterado')}</b><small>{new Date(c.at).toLocaleString(locales[lang])}</small><details><summary>{t('Ver alteração')}</summary><p>{t('Antes')}: {describe(c.before,c.kind)}</p><p>{t('Depois')}: {describe(c.after,c.kind)}</p></details></div>{c.before&&(c.kind==='record'||c.kind==='shift')&&<button className="secondary" disabled={busy} onClick={()=>{setRestore(c);setError('')}}>{t('Recuperar')}</button>}</article>)}<AlertDialog open={!!restore} onOpenChange={v=>{if(!v&&!busy)setRestore(null)}}><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>{t('Recuperar versão anterior?')}</AlertDialogTitle><AlertDialogDescription>{t('O registo será restaurado e o saldo recalculado. A recuperação também fica no histórico.')}</AlertDialogDescription></AlertDialogHeader>{error&&<p role="alert" className="error">{t(error)}</p>}<AlertDialogFooter><AlertDialogCancel disabled={busy}>{t('Voltar')}</AlertDialogCancel><AlertDialogAction disabled={busy} onClick={e=>{e.preventDefault();void recover()}}>{t('Recuperar')}</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog></section>
}
