'use client';
import {useEffect,useState} from 'react';
import {Download,Check} from 'lucide-react';
import {translate,type Language} from '@/lib/i18n';
type InstallPrompt=Event & {prompt:()=>Promise<void>;userChoice:Promise<unknown>};
export function InstallApp({lang}:{lang:Language}){const t=(s:string)=>translate(lang,s),[prompt,setPrompt]=useState<InstallPrompt|null>(null),[installed,setInstalled]=useState(false),[ios,setIos]=useState(false),[error,setError]=useState(false);
useEffect(()=>{let live=true;queueMicrotask(()=>{if(!live)return;setInstalled(window.matchMedia('(display-mode: standalone)').matches||(navigator as Navigator & {standalone?:boolean}).standalone===true);setIos(/iPad|iPhone|iPod/.test(navigator.userAgent));});const before=(e:Event)=>{e.preventDefault();setPrompt(e as InstallPrompt)},after=()=>{setInstalled(true);setPrompt(null)};window.addEventListener('beforeinstallprompt',before);window.addEventListener('appinstalled',after);if('serviceWorker'in navigator)navigator.serviceWorker.register('/sw.js').catch(()=>{});return()=>{live=false;window.removeEventListener('beforeinstallprompt',before);window.removeEventListener('appinstalled',after)}},[]);
return <section className="install-card"><h3>{t('Instalar no telemóvel')}</h3>{installed?<p className="notice"><Check size={18}/>{t('A aplicação está instalada neste dispositivo.')}</p>:<>{prompt?<button className="primary" onClick={async()=>{try{setError(false);await prompt.prompt();await prompt.userChoice;setPrompt(null)}catch{setError(true)}}}><Download size={18}/>{t('Instalar Zeitkonto')}</button>:<p className="muted">{t(ios?'No Safari, abre Partilhar e escolhe Adicionar ao ecrã principal.':'No menu do navegador, procura Instalar aplicação ou Adicionar ao ecrã principal.')}</p>}{error&&<p role="alert" className="error">{t('Usa o menu do navegador para instalar a aplicação.')}</p>}</>}<p className="muted">{t('Instalação pelo navegador. Ainda não está disponível na Google Play nem na App Store. Ativa o registo sem internet abaixo para usar entrada, pausas e saída offline.')}</p></section>
}
