'use client';
import {holidayLabel} from '@/lib/holiday-label';
import {analytics} from '@/lib/local-sync';
import {BalanceOverview} from './balance-overview';
import {useState} from 'react';
import {calendarPrintHtml,annualCalendarPrintHtml} from '@/lib/calendar-print';
import {Calendar,CalendarDayButton} from '@/components/ui/calendar';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select';
import {pt,de,enGB,tr} from 'date-fns/locale';
import {Plus,Palmtree,Coffee,HeartPulse,Printer} from 'lucide-react';
import {type State,type Entry,type LeaveKind,entryKindLabel,annualSummary,dateLocal} from '@/lib/time';
import {type Language,translate,locales,formatMinutes} from '@/lib/i18n';
import {countryCodes,germanRegions,relevantHolidays} from '@/lib/leave';
import {useHolidays} from '@/lib/use-holidays';
export function LeaveCalendar({data,lang,email,busy,save,onAdd,onEdit}:{data:State;lang:Language;email:string;busy:boolean;save:(s:State)=>Promise<boolean|undefined>;onAdd:(kind:LeaveKind,date:string)=>void;onEdit:(r:Entry)=>void}){
 const t=(s:string)=>translate(lang,s),[month,setMonth]=useState(new Date()),[selected,setSelected]=useState<Date|undefined>(new Date()),h=useHolidays(data.country,[month.getFullYear()]);
 const region=data.region.startsWith(data.country+'-')?data.region:'',rows=relevantHolidays(h.rows,region),selectedDate=dateLocal(selected??new Date()),record=data.records.find(r=>r.date===selectedDate),todayHolidays=rows.filter(r=>r.date===selectedDate);
 const regions=data.country==='DE'?Object.keys(germanRegions):Array.from(new Set(h.rows.flatMap(r=>r.counties??[]))).sort();
 const regionLabel=(code:string)=>germanRegions[code]??code;
 const entryLabel=(r:Entry)=>r.kind==='holiday'?holidayLabel(r,lang):t(entryKindLabel(r.kind));
 const [printError,setPrintError]=useState(false),[printScope,setPrintScope]=useState('year');
 const summary=annualSummary(data,month.getFullYear());
 function printMonth(){analytics('export');setPrintError(false);const popup=window.open('','_blank');if(!popup){setPrintError(true);return}popup.opener=null;popup.document.open();popup.document.write(printScope==='year'?annualCalendarPrintHtml(data,month.getFullYear(),lang,email,rows):calendarPrintHtml(data,month,lang,email,rows));popup.document.close();popup.document.getElementById('print')?.addEventListener('click',()=>popup.print());popup.focus();setTimeout(()=>{if(!popup.closed)popup.print()},400)}
 return <section className="panel leave-panel"><div className="section-head"><div><h2>{t('Calendário de ausências')}</h2><p className="muted">{t('Seleciona um dia para consultar ou marcar um período.')}</p></div><button className="primary" disabled={busy} onClick={()=>onAdd('holiday',selectedDate)}><Plus size={18}/>{t('Marcar período')}</button></div>
 <div className="calendar-export"><label>{t('Período de impressão')}<Select value={printScope} onValueChange={setPrintScope}><SelectTrigger className="select-input"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="year">{t('Ano completo')}</SelectItem><SelectItem value="month">{t('Mês apresentado')}</SelectItem></SelectContent></Select></label><label>{t('Ano')}<Select value={String(month.getFullYear())} onValueChange={v=>setMonth(new Date(Number(v),month.getMonth(),1))}><SelectTrigger className="select-input"><SelectValue/></SelectTrigger><SelectContent>{Array.from({length:16},(_,i)=>2020+i).map(y=><SelectItem key={y} value={String(y)}>{y}</SelectItem>)}</SelectContent></Select></label><button type="button" className="secondary" disabled={busy||h.loading||!!h.error} onClick={printMonth}><Printer size={18}/>{t('Imprimir / Guardar PDF')}</button><p className="muted">{t(printScope==='year'?'Exporta os 12 meses e todos os registos do ano.':'Exporta o mês apresentado, com férias, doença, descanso e turnos.')}</p></div>{printError&&<p className="error" role="alert">{t('Permite abrir uma nova janela e tenta novamente.')}</p>}
 <BalanceOverview data={data} year={month.getFullYear()} lang={lang}/>
 <div className="calendar-filters"><label>{t('País dos feriados')}<Select value={data.country} disabled={busy} onValueChange={country=>save({...data,country:country as State['country'],region:country==='DE'?'DE-NW':''})}><SelectTrigger className="select-input"><SelectValue/></SelectTrigger><SelectContent>{countryCodes.map(c=><SelectItem value={c} key={c}>{new Intl.DisplayNames([locales[lang]],{type:'region'}).of(c)}</SelectItem>)}</SelectContent></Select></label><label>{t('Região / Bundesland')}<Select value={region||'national'} disabled={busy||h.loading} onValueChange={v=>save({...data,region:v==='national'?'':v})}><SelectTrigger className="select-input"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="national">{t('Apenas feriados nacionais')}</SelectItem>{regions.map(r=><SelectItem key={r} value={r}>{regionLabel(r)}</SelectItem>)}</SelectContent></Select></label></div>
 <div className="calendar-legend"><span className="legend-vacation">{t('Férias')}</span><span className="legend-rest">{t('Descanso compensatório')}</span><span className="legend-public">{t('Feriado')}</span><span className="legend-sick-note">{t('Doença com atestado')}</span><span className="legend-sick-no-note">{t('Doença sem atestado')}</span><span className="legend-work">{t('Turno de trabalho')}</span></div>
 {h.loading&&<p role="status" className="muted">{t('A carregar feriados…')}</p>}{h.error&&<div className="error" role="alert">{t('Não foi possível carregar os feriados.')} <button onClick={h.retry}>{t('Tentar novamente')}</button></div>}
 <div className="calendar-layout"><Calendar className="leave-calendar" mode="single" month={month} onMonthChange={setMonth} selected={selected} onSelect={setSelected} startMonth={new Date(2020,0)} endMonth={new Date(2035,11)} locale={{pt,de,en:enGB,tr}[lang]} weekStartsOn={1} modifiers={{sickNote:data.records.filter(r=>r.kind==='sick_note').map(r=>new Date(r.date+'T12:00:00')),sickNoNote:data.records.filter(r=>r.kind==='sick_no_note').map(r=>new Date(r.date+'T12:00:00')),vacation:data.records.filter(r=>r.kind==='holiday').map(r=>new Date(r.date+'T12:00:00')),rest:data.records.filter(r=>r.kind==='rest').map(r=>new Date(r.date+'T12:00:00')),publicHoliday:rows.map(r=>new Date(r.date+'T12:00:00')),work:data.records.filter(r=>r.kind==='work').map(r=>new Date(r.date+'T12:00:00'))}} modifiersClassNames={{sickNote:'cal-sick-note',sickNoNote:'cal-sick-no-note',vacation:'cal-vacation',rest:'cal-rest',publicHoliday:'cal-public',work:'cal-work'}} components={{DayButton:props=>{const d=dateLocal(props.day.date),e=data.records.find(r=>r.date===d),hol=rows.filter(r=>r.date===d),description=[e?entryLabel(e):'',...hol.map(r=>r.localName)].filter(Boolean).join(' · ');return <CalendarDayButton {...props} data-partial={e?.kind==='holiday'&&e.holidayMode&&e.holidayMode!=='full'&&e.holidayMode!=='company_half'?true:undefined} title={description||undefined} aria-label={[props['aria-label'],description].filter(Boolean).join(' · ')}/>}}}/>
 <aside className="calendar-detail"><h3>{(selected??new Date()).toLocaleDateString(locales[lang],{day:'numeric',month:'long',year:'numeric'})}</h3>{todayHolidays.map((r,i)=><p key={i} className="holiday-name">{r.localName}{lang==='en'&&r.name!==r.localName?' · '+r.name:''}</p>)}{record?<><p className="selected-entry">{entryLabel(record)}</p>{record.kind==='work'&&<p>{record.start} – {record.end}</p>}{record.note&&<p className="muted">{record.note}</p>}<button className="secondary" disabled={busy} onClick={()=>onEdit(record)}>{t('Editar registo')}</button></>:<><p className="muted">{t('Sem registos neste dia.')}</p><button className="secondary" disabled={busy} onClick={()=>onAdd('holiday',selectedDate)}><Palmtree size={18}/>{t('Marcar férias')}</button><button className="secondary" disabled={busy} onClick={()=>onAdd('rest',selectedDate)}><Coffee size={18}/>{t('Usar horas acumuladas')}</button><button className="secondary" disabled={busy} onClick={()=>onAdd('sick_no_note',selectedDate)}><HeartPulse size={18}/>{t('Registar doença')}</button></>}
 <h3 className="month-holiday-title">{t('Feriados neste mês')}</h3>{rows.filter(r=>r.date.startsWith(dateLocal(month).slice(0,7))).map((r,i)=><p className="holiday-list-item" key={r.date+i}><b>{r.date.slice(8)}</b><span>{r.localName}</span></p>)}{!h.loading&&!h.error&&!rows.some(r=>r.date.startsWith(dateLocal(month).slice(0,7)))&&<p className="muted">{t('Sem feriados neste mês.')}</p>}</aside></div>
 <p className="muted holiday-source">{t('Fonte dos feriados')}: <a href="https://github.com/nager/Nager.Date" target="_blank" rel="noreferrer">Nager.Date</a>. {t('Feriados municipais e exceções locais podem não estar incluídos. Os feriados não alteram o saldo automaticamente.')}</p></section>
}
