'use client';
import {ClockInput} from './clock-input';
import {DurationInput} from './duration-input';
import {useState} from 'react';
import {Pencil,Copy,Trash2} from 'lucide-react';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {dateLocal,type State} from '@/lib/time';
import {replacePlanned,copyPeriod,type Planned} from '@/lib/planned-shifts';
import {translate,locales,formatMinutes,type Language} from '@/lib/i18n';
import '@/lib/improvements-i18n';
export function ShiftManager({data,lang,busy,save}:{data:State;lang:Language;busy:boolean;save:(s:State)=>Promise<boolean>}){const t=(s:string)=>translate(lang,s),[draft,setDraft]=useState<Planned|null>(null),[editing,setEditing]=useState<string|null>(null),[bulk,setBulk]=useState<'edit'|'copy'|null>(null),[from,setFrom]=useState(dateLocal()),[to,setTo]=useState(dateLocal()),[destination,setDestination]=useState(dateLocal()),[start,setStart]=useState('06:00'),[end,setEnd]=useState('14:45'),[hours,setHours]=useState(String(data.dailyMinutes/60)),[error,setError]=useState('');
 async function commit(updates:Planned[],removed:string[]=[]){try{if(await save({...data,shifts:replacePlanned(data.shifts,updates,removed)})){setDraft(null);setBulk(null);setError('')}}catch(e){setError((e as Error).message)}}
 const selected=data.shifts.filter(s=>s.date>=from&&s.date<=to);
 return <section className="panel shift-list"><div className="section-head"><h2>{t('Turnos planeados')}</h2><div className="account-actions"><button className="secondary" disabled={busy} onClick={()=>{setBulk('edit');setError('')}}>{t('Editar período')}</button><button className="secondary" disabled={busy} onClick={()=>{setBulk('copy');setError('')}}>{t('Copiar período')}</button></div></div>{!data.shifts.length?<p className="muted">{t('Ainda não há turnos planeados.')}</p>:data.shifts.slice().sort((a,b)=>a.date.localeCompare(b.date)).map(s=><article className="record" key={s.id}><div className="record-info"><b>{new Date(s.date+'T12:00:00').toLocaleDateString(locales[lang])} · {s.name}</b><small>{s.start}–{s.end} {s.end<s.start?t('(+1 dia)'):''} · {formatMinutes(lang,s.targetMinutes)}</small>{data.records.some(r=>r.date===s.date&&r.kind!=='work')&&<small>{t('Ausência marcada: sem aviso')}</small>}</div><button className="icon-button" disabled={busy} aria-label={t('Editar turno')} onClick={()=>{setDraft(s);setEditing(s.id);setError('')}}><Pencil size={18}/></button><button className="icon-button" disabled={busy} aria-label={t('Copiar turno')} onClick={()=>{setDraft({...s,id:crypto.randomUUID()});setEditing(null);setError('')}}><Copy size={18}/></button><button className="icon-button" disabled={busy} aria-label={t('Remover turno planeado')} onClick={()=>void commit([], [s.id])}><Trash2 size={18}/></button></article>)}
 <Dialog open={!!draft||!!bulk} onOpenChange={v=>{if(!v&&!busy){setDraft(null);setBulk(null)}}}><DialogContent className="entry-dialog"><DialogHeader><DialogTitle>{t(bulk?(bulk==='copy'?'Copiar período':'Editar período'):editing?'Editar turno':'Copiar turno')}</DialogTitle><DialogDescription>{t('Os registos de trabalho concluídos não são alterados. Os lembretes seguem o novo horário.')}</DialogDescription></DialogHeader><form onSubmit={e=>{e.preventDefault();setError('');if(draft){void commit([draft],editing?[editing]:[])}else if(bulk){try{if(!selected.length)throw Error('Não há turnos neste período.');void commit(bulk==='copy'?copyPeriod(data.shifts,from,to,destination):selected.map(s=>({...s,start,end,targetMinutes:Math.round(Number(hours)*60)})),bulk==='edit'?selected.map(s=>s.id):[])}catch(e){setError((e as Error).message)}}}}>{draft?<><label>{t('Nome do turno')}<input required maxLength={60} value={draft.name} onChange={e=>setDraft({...draft,name:e.target.value})}/></label><label>{t('Data')}<input type="date" required value={draft.date} onChange={e=>setDraft({...draft,date:e.target.value})}/></label><div className="field-row"><label>{t('Entrada')}<ClockInput lang={lang} value={draft.start} onChange={value=>setDraft({...draft,start:value})}/></label><label>{t('Saída')}<ClockInput lang={lang} value={draft.end} onChange={value=>setDraft({...draft,end:value})}/></label></div><label>{t('Horas previstas por dia')} <span className="muted">(HH:MM)</span><DurationInput minutes={draft.targetMinutes} min={15} max={1440} onChange={m=>setDraft({...draft,targetMinutes:m})}/></label></>:<><div className="field-row"><label>{t('De')}<input required type="date" value={from} onChange={e=>setFrom(e.target.value)}/></label><label>{t('Até')}<input required type="date" min={from} value={to} onChange={e=>setTo(e.target.value)}/></label></div><p>{selected.length} {t('turnos selecionados')}</p>{bulk==='copy'?<label>{t('Copiar para período a começar em')}<input type="date" required value={destination} onChange={e=>setDestination(e.target.value)}/></label>:<><div className="field-row"><label>{t('Entrada')}<ClockInput lang={lang} value={start} onChange={setStart}/></label><label>{t('Saída')}<ClockInput lang={lang} value={end} onChange={setEnd}/></label></div><label>{t('Horas previstas por dia')} <span className="muted">(HH:MM)</span><DurationInput minutes={Number(hours)*60} min={15} max={1440} onChange={m=>setHours(String(m/60))}/></label></>}</>}{error&&<p className="error" role="alert">{t(error)}</p>}<button className="primary" disabled={busy}>{t('Guardar alterações')}</button></form></DialogContent></Dialog>{error&&!draft&&!bulk&&<p className="error" role="alert">{t(error)}</p>}</section>
}
