'use client';
import {useState} from 'react';
import {ArrowLeft,ChevronLeft,ChevronRight,CalendarDays,Pencil,Trash2,X} from 'lucide-react';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {dateLocal,weekStart,workWeek,summaryWeek,weeklySummary,entryKindLabel,type State,type Entry} from '@/lib/time';
import {translate,locales,type Language} from '@/lib/i18n';
import {holidayLabel} from '@/lib/holiday-label';
import '@/lib/timesheet-i18n';
const shiftDate=(date:string,days:number)=>{const d=new Date(date+'T12:00:00');d.setDate(d.getDate()+days);return dateLocal(d)};
const clock=(minutes:number)=>`${Math.floor(Math.abs(Math.round(minutes))/60)}:${String(Math.abs(Math.round(minutes))%60).padStart(2,'0')}`;
const worked=(rows:Entry[])=>rows.filter(r=>r.kind==='work').reduce((n,r)=>n+Math.max(0,r.targetMinutes+r.delta),0);
export function WeeklyTimesheet({data,lang,busy,onAdd,onEdit,onDelete,onBack}:{data:State;lang:Language;busy:boolean;onAdd:(date:string)=>void;onEdit:(entry:Entry)=>void;onDelete:(id:string)=>void;onBack:()=>void}){
 const [chosenWeek,setWeek]=useState<string|null>(null),[selected,setSelected]=useState<string|null>(null);
 const week=chosenWeek??summaryWeek(data,dateLocal());
 const t=(s:string)=>translate(lang,s),format=(date:string,options:Intl.DateTimeFormatOptions)=>new Date(date+'T12:00:00').toLocaleDateString(locales[lang],options);
 const days=Array.from({length:7},(_,i)=>shiftDate(week,i)),rows=(date:string)=>data.records.filter(r=>r.date===date),counted=(date:string)=>rows(date).filter(r=>r.kind!=='work'||workWeek(r)===week);
 const totals=weeklySummary(data,dateLocal(),week),end=days[6];
 const carried=rows(shiftDate(week,-1)).filter(r=>r.kind==='work'&&workWeek(r)===week);
 const range=`${format(week,{day:'numeric',month:'short'})} – ${format(end,{day:'numeric',month:'short',year:'numeric'})}`;
 const move=(amount:number)=>{setWeek(shiftDate(week,amount));if(selected)setSelected(shiftDate(selected,amount))};
 const dayRows=selected?rows(selected):[],dayWorked=worked(dayRows);
 const strip=<div className="ts-week-strip" aria-label={t('Dias da semana')}>{days.map(date=>{const entries=counted(date),kind=entries[0]?.kind;return <button type="button" key={date} aria-pressed={date===selected} aria-label={`${format(date,{weekday:'long',day:'numeric',month:'long'})}: ${entries.length?t('Com registos'):t('Sem registos')}`} onClick={()=>setSelected(date)}><span className="ts-weekday">{format(date,{weekday:'short'})}</span><span className={`ts-dot ${kind==='work'?'work':kind==='holiday'?'holiday':kind==='rest'?'rest':kind==='sick_no_note'?'sick-unverified':kind?'sick':'ts-empty'}`}>{entries.length?'✓':''}</span><span>{format(date,{day:'numeric'})}</span></button>})}</div>;
 const arrows=<div className="ts-arrows"><button type="button" className="icon-button" onClick={()=>move(-7)} aria-label={t('Semana anterior')}><ChevronLeft/></button><button type="button" className="icon-button" onClick={()=>move(7)} aria-label={t('Semana seguinte')}><ChevronRight/></button></div>;
 return <section className="timesheet"><header className="ts-title"><button type="button" className="icon-button" onClick={onBack} aria-label={t('Voltar')}><ArrowLeft/></button><h2>{t('Resumo semanal')}</h2><label className="ts-date-picker"><CalendarDays/><span className="sr-only">{t('Escolher data')}</span><input aria-label={t('Escolher data')} type="date" value={week} onChange={e=>{if(/^\d{4}-\d{2}-\d{2}$/.test(e.target.value))setWeek(summaryWeek({...data,active:null},e.target.value))}}/></label></header>
 <div className="ts-section"><div className="ts-week-heading"><h3>{range}</h3>{arrows}</div><dl className="ts-totals"><div><dt>{t('Horas registadas')}</dt><dd>{clock(totals.worked)}</dd></div><div><dt>{t('Ausências creditadas')}</dt><dd>{clock(totals.justified)}</dd></div><div><dt>{t('Objetivo semanal')}</dt><dd>40:00</dd></div><div><dt>{t('Horas extra')}</dt><dd className="positive">+{clock(totals.balance)}</dd></div></dl></div>
 <div className="ts-section"><h3>{t('Resumo semanal')}</h3>{strip}<div className="ts-legend"><span>✓ {t('Com registos')}</span><span>○ {t('Sem registos')}</span></div></div>
 <div className="ts-section"><p className="ts-note">{t('A noite de domingo conta uma única vez, na semana seguinte. Férias e doença não reduzem o banco de horas.')}</p><p className="ts-muted">{t('Dias')} · {t('Registado / previsto')}</p>{carried.length>0&&<><p className="ts-note">{t('Noite de domingo incluída nesta semana')}</p><button type="button" className="ts-day-row" onClick={()=>setSelected(shiftDate(week,-1))}><span><b>{format(shiftDate(week,-1),{weekday:'long'})}</b><span>{format(shiftDate(week,-1),{day:'numeric',month:'long'})}</span></span><span>{clock(worked(carried))}<ChevronRight size={18}/></span></button></>}{days.map(date=>{const entries=counted(date);return <button type="button" className="ts-day-row" key={date} onClick={()=>setSelected(date)}><span><b>{format(date,{weekday:'long'})}</b><span>{format(date,{day:'numeric',month:'long'})}</span>{rows(date).some(r=>r.kind==='work'&&workWeek(r)!==week)&&<small>{t('Conta para a semana seguinte')}</small>}{entries.some(r=>r.kind!=='work')&&<small>{entries.filter(r=>r.kind!=='work').map(r=>t(entryKindLabel(r.kind))).join(' · ')}</small>}</span><span>{clock(worked(entries))} / {entries.some(r=>r.kind==='work')?clock(entries.filter(r=>r.kind==='work').reduce((n,r)=>n+r.targetMinutes,0)):'—'}<ChevronRight size={18}/></span></button>})}</div>
 <Dialog open={selected!==null} onOpenChange={value=>{if(!value)setSelected(null)}}><DialogContent className="ts-day-dialog" style={{position:"fixed",inset:0,margin:"auto",translate:"none",transform:"none",animation:"none",width:"min(680px, 100vw)",maxWidth:"100vw",height:"min(900px, 100dvh)",maxHeight:"100dvh"}} showCloseButton={false}><header className="ts-title"><button type="button" className="icon-button" onClick={()=>setSelected(null)} aria-label={t('Fechar')}><X/></button><DialogTitle>{selected&&format(selected,{day:'2-digit',month:'2-digit',year:'numeric'})}</DialogTitle><CalendarDays/></header><DialogDescription className="sr-only">{t('Detalhe diário de horas e pausas')}</DialogDescription><div className="ts-section"><div className="ts-week-heading"><h3>{range}</h3>{arrows}</div>{strip}</div><div className="ts-section"><strong className="ts-big-time">{clock(dayWorked)}</strong><p className="ts-muted">{t('Horas registadas')}</p></div><div className="ts-section"><h3>{t('Registos')}</h3>{!dayRows.length&&<p className="ts-muted">{t('Sem registos')}</p>}{dayRows.map(r=><article className="ts-entry" key={r.id}><b>{r.kind==='work'?`${r.start} – ${r.end}${r.end<r.start?' (+1 '+t('dia')+')':''}`:r.kind==='holiday'?holidayLabel(r,lang):t(entryKindLabel(r.kind))}</b><p>{t(entryKindLabel(r.kind))}</p>{r.kind==='work'&&<><p>{t('Tempo previsto')}: {clock(r.targetMinutes)}</p><p>{t('Pausas')}: {clock(r.pause)} · {t('Pausa incluída')}: {clock(Math.min(r.pause,r.includedPause))}</p>{workWeek(r)!==weekStart(r.date)&&<p className="ts-note">{t('Conta para a semana seguinte')}</p>}</>}{r.note&&<p>{r.note}</p>}<div className="ts-entry-actions"><button type="button" className="secondary" disabled={busy} onClick={()=>{setSelected(null);onEdit(r)}}><Pencil size={17}/>{t('Editar registo')}</button><button type="button" className="icon-button" disabled={busy} aria-label={t('Eliminar registo')} onClick={()=>{setSelected(null);onDelete(r.id)}}><Trash2 size={18}/></button></div></article>)}<button type="button" className="ts-create" disabled={busy} onClick={()=>{if(selected){const date=selected;setSelected(null);onAdd(date)}}}>{t('Criar registo')}</button></div><footer className="ts-footer"><button type="button" className="primary" onClick={()=>setSelected(null)}>{t('Ver resumo semanal')}</button></footer></DialogContent></Dialog>
 </section>;
}
